/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component, useEffect} from 'react';
import {Platform, StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import RNMasterpassKit from 'react-native-masterpass-kit';

export default function App() {
  useEffect(() => {
    const subcription = RNMasterpassKit.registerUserDidCancelEvent(() => {
      console.warn('User cancelled');
    });
    return () => {
      // Remove subscriptions
      subcription.remove();
    };
  }, []);

  function handleCheckout() {
    RNMasterpassKit.checkout({
      code: '6799782555',
      apiKey: '1234567890',
      system: 'test',
    });
  }

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆MasterpassKit example☆</Text>
      <TouchableOpacity style={styles.button} onPress={handleCheckout}>
        <Text>Checkout</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  button: {
    padding: 15,
    backgroundColor: 'green',
  },
});
